src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 */
class Cliente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alias;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $apellido1;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $apellido2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $domicilio;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $codigoPostal;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fechaNacimiento;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profesion;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comentarios;

    /**
     * @ORM\Column(type="string", length=9, nullable=true)
     */
    private $movil;

    /**
     * @ORM\Column(type="string", length=9, nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fechaAlta;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $nif;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $idAnterior;

    /**
     * @ORM\ManyToOne(targetEntity=Localidad::class, inversedBy="clientes")
     */
    private $localidad;

    /**
     * @ORM\OneToMany(targetEntity=Factura::class, mappedBy="cliente")
     */
    private $facturas;

    /**
     * @ORM\OneToMany(targetEntity=Tratamiento::class, mappedBy="cliente")
     */
    private $tratamientos;


    public function __construct()
    {
        $this->facturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAlias(): ?string
    {
        return $this->alias;
    }

    public function setAlias(?string $alias): self
    {
        $this->alias = $alias;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(?string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido1(): ?string
    {
        return $this->apellido1;
    }

    public function setApellido1(?string $apellido1): self
    {
        $this->apellido1 = $apellido1;

        return $this;
    }

    public function getApellido2(): ?string
    {
        return $this->apellido2;
    }

    public function setApellido2(?string $apellido2): self
    {
        $this->apellido2 = $apellido2;

        return $this;
    }

    public function getDomicilio(): ?string
    {
        return $this->domicilio;
    }

    public function setDomicilio(?string $domicilio): self
    {
        $this->domicilio = $domicilio;

        return $this;
    }

    public function getCodigoPostal(): ?string
    {
        return $this->codigoPostal;
    }

    public function setCodigoPostal(?string $codigoPostal): self
    {
        $this->codigoPostal = $codigoPostal;

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fechaNacimiento;
    }

    public function setFechaNacimiento(?\DateTimeInterface $fechaNacimiento): self
    {
        $this->fechaNacimiento = $fechaNacimiento;

        return $this;
    }

    public function getProfesion(): ?string
    {
        return $this->profesion;
    }

    public function setProfesion(?string $profesion): self
    {
        $this->profesion = $profesion;

        return $this;
    }

    public function getComentarios(): ?string
    {
        return $this->comentarios;
    }

    public function setComentarios(?string $comentarios): self
    {
        $this->comentarios = $comentarios;

        return $this;
    }

    public function getMovil(): ?string
    {
        return $this->movil;
    }

    public function setMovil(?string $movil): self
    {
        $this->movil = $movil;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return $this
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFechaAlta(): ?\DateTimeInterface
    {
        return $this->fechaAlta;
    }

    /**
     * @param$fechaAlta
     * @return $this
     */
    public function setFechaAlta(?\DateTime  $fechaAlta): self
    {
        $this->fechaAlta = $fechaAlta;

        return $this;
    }

    public function getNif(): ?string
    {
        return $this->nif;
    }

    public function setNif(?string $nif): self
    {
        $this->nif = $nif;

        return $this;
    }

    public function getLocalidad(): ?Localidad
    {
        return $this->localidad;
    }

    public function setLocalidad(?Localidad $localidad): self
    {
        $this->localidad = $localidad;

        return $this;
    }

    /**
     * @return Collection|Factura[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Factura $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setCliente($this);
        }

        return $this;
    }

    public function removeFactura(Factura $factura): self
    {
        if ($this->facturas->removeElement($factura)) {
            // set the owning side to null (unless already changed)
            if ($factura->getCliente() === $this) {
                $factura->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tratamiento[]
     */
    public function getTratamientos(): ?Collection
    {
        return $this->tratamientos;
    }

    public function addTratamiento(Tratamiento $tratamiento): self
    {
        if (!$this->tratamientos->contains($tratamiento)) {
            $this->tratamientos[] = $tratamiento;
            $tratamiento->setCliente($this);
        }

        return $this;
    }

    public function removeTratamiento(Tratamiento $tratamiento): self
    {
        if ($this->tratamientos->removeElement($tratamiento)) {
            // set the owning side to null (unless already changed)
            if ($tratamiento->getCliente() === $this) {
                $tratamiento->setCliente(null);
            }
        }

        return $this;
    }
    /**
     * @return mixed
     */
    public function getIdAnterior()
    {
        return $this->idAnterior;
    }

    /**
     * @param mixed $idAnterior
     */
    public function setIdAnterior($idAnterior): void
    {
        $this->idAnterior = $idAnterior;
    }

    public function __toString()
    {
     return $this->apellido1. ' '.$this->apellido2.', '.$this->nombre;   // TODO: Implement __toString() method.
    }

    public function getApenom() {
        return $this->getApellido1().' '.$this->getApellido2().', '.$this->getNombre();
    }
}

src/Controller/FacturaController.php
<?php

namespace App\Controller;

use App\Entity\Factura;
use App\Entity\FacturaLinea;
use App\Entity\Tratamiento;
use App\Entity\TratamientoConcepto;
use App\Form\FacturaType;
use App\Form\FiltroFechasType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Connection;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use PhpOffice\PhpSpreadsheet\Calculation\DateTime;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\Routing\Annotation\Route;

class FacturaController extends AbstractController
{
    /**
     * @Route("/factura/query/", name="query_facturas")
     * @param Request $request
     * @return JsonResponse|Response
     */

    public function queryFacturas(Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $Facturas = $em->getRepository("App:Factura")
            ->createQueryBuilder('u')
            ->orderBy('u.serie, u.numero')
            ->getQuery()->getResult() ;

        return $this->render('factura/queryFacturas.html.twig', [
            'facturas' => $Facturas
        ]);
    }

    /**
     * @Route("/factura/query/cliente/{cliente_id}", name="query_facturas_cliente")
     * @param $cliente_id
     * @return JsonResponse|Response
     */

    public function queryFacturasCliente(int $cliente_id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $Cliente = $em->getRepository("App:Cliente")->find($cliente_id);
        $Facturas = $em->getRepository("App:Factura")->findBy(["cliente" => $Cliente]);

        return $this->render('factura/queryFacturas.html.twig', [
            'facturas' => $Facturas
        ]);
    }

    /**
     * @Route("/factura/ver/{factura_id}", name="ver_factura")
     * @param Request $request
     * @param int $factura_id
     * @return Response
     */
    public function verFactura(Request $request, int $factura_id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $Factura = $em->getRepository("App:Factura")->find($factura_id);

        $form = $this->createForm(FacturaType::class, $Factura);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $this->addFlash("info", "Factura Modificada correctamente");
            $em->persist($Factura);
            $em->flush();
            return $this->redirectToRoute('ver_factura', ["factura_id" => $Factura->getId()]);
        }

        return $this->render('factura/editFactura.html.twig', [
            'factura' => $Factura,
            'lineas' => $Factura->getfacturaLineas(),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/factura/generar/{tratamiento_id}", name="generar_factura")
     * @param int $tratamiento_id
     * @return Response
     * @throws \Doctrine\DBAL\Exception
     */
    public function generarFactura(int $tratamiento_id): Response
    {
        $em = $this->getDoctrine()->getManager();

        /** @var Tratamiento $Tratamiento */
        $Tratamiento = $em->getRepository("App:Tratamiento")->find($tratamiento_id);

        if (is_null($Tratamiento->getCliente()->getNif())) {
            $this->addFlash("error", "CLIENTE SIN NIF NO SE PUEDE GENERAR FACTURA");
            return $this->redirectToRoute("edit_cliente", ["cliente_id" => $Tratamiento->getCliente()->getId()]);
        }

        if ($Tratamiento->getConceptos()->isEmpty()) {
            $this->addFlash("error", "TRATAMIENTO SIN CONCEPTOS NO SE PUEDE GENERAR FACTURA");
            return $this->redirectToRoute("edit_tratamiento", ["tratamiento_id" => $Tratamiento->getId()]);
        }

        if (is_null($Tratamiento->getCliente()->getDomicilio())) {
            $this->addFlash("error", "CLIENTE SIN DOMICILIO NO SE PUEDE GENERAR FACTURA");
            return $this->redirectToRoute("edit_cliente", ["cliente_id" => $Tratamiento->getCliente()->getId()]);
        }

        $serie = $Tratamiento->getFechaTratamiento()->format("Y");
        $query = "select max(numero)+1 as siguienteNumero from factura where serie = " . $serie;
        /** @var Connection $con */
        $con = $this->getDoctrine()->getConnection();
        $st = $con->executeQuery($query);
        $resultado = $st->fetch();

        $Factura = new Factura();
        $Factura->setCliente($Tratamiento->getCliente());
        $Factura->setTratamiento($Tratamiento);
        $Factura->setSerie($serie);
        $Factura->setNumero($resultado["siguienteNumero"]);
        $Factura->setFechaFactura($Tratamiento->getFechaTratamiento());
        $Factura->setTotalConcepto(0);
        $Factura->setTotalCuotaIva(0);
        $Factura->setTotalfactura(0);
        $em->persist($Factura);
        $em->flush();
        $totalConcepto = 0;
        $totalCuotaIva = 0;
        $totalfactura = 0;
        $Conceptos = $em->getRepository("App:TratamientoConcepto")->findBy(["tratamiento" => $Tratamiento]);
        /** @var TratamientoConcepto $concepto */
        foreach ($Conceptos as $concepto) {
            $FacturaLinea = new FacturaLinea();
            $FacturaLinea->setFactura($Factura);
            $FacturaLinea->setImporteTotal($concepto->getImporteTotal());
            $FacturaLinea->setCuotaIva($concepto->getCuotaIva());
            $FacturaLinea->setPorcentajeIva($concepto->getPorcentajeIva());
            $FacturaLinea->setImporteConcepto($concepto->getImporteConcepto());
            $FacturaLinea->setImporteUnitario($concepto->getImporteUnitario());
            $FacturaLinea->setUnidades($concepto->getUnidades());
            $FacturaLinea->setConcepto($concepto->getDescripcion());
            $em->persist($FacturaLinea);
            $em->flush();
            $totalConcepto = $totalConcepto + $concepto->getImporteConcepto();
            $totalCuotaIva = $totalCuotaIva + $concepto->getCuotaIva();
            $totalfactura = $totalfactura + $concepto->getImporteTotal();
        }

        $Factura->setTotalConcepto($totalConcepto);
        $Factura->setTotalCuotaIva($totalCuotaIva);
        $Factura->setTotalfactura($totalfactura);
        $em->persist($Factura);
        $em->flush();

        $this->addFlash("info", "Factura Generada Correctamente");
        return $this->redirectToRoute("ver_factura", ["factura_id" => $Factura->getId()]);
    }


    /**
     * @Route("/factura/delete/{factura_id}",options={"expose"=true}, name="delete_factura")
     */
    public function deleteFactura(int $factura_id): Response
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Factura $Factura */
        $Factura = $em->getRepository("App:Factura")->find($factura_id);
        $this->addFlash("info", "Factura "
            . $Factura->getNumero()
            . "/"
            . $Factura->getSerie()
            . " de "
            . $Factura->getFechaFactura()->format('d/m/Y')
            . "eliminada correctamente");
        $em->remove($Factura);
        $em->flush();

        return $this->redirectToRoute("query_facturas");
    }


    /**
     * @Route("/factura/imprimir/{factura_id}",options={"expose"=true}, name="imprimir_factura",)
     * @param int $factura_id
     * @return Response
     */
    public function imprimirFactura(int $factura_id, Pdf $pdf): Response
    {
        $em = $this->getDoctrine()->getManager();
        /** @var Factura $Factura */
        $Factura = $em->getRepository("App:Factura")->find($factura_id);
        $html = $this->renderView('factura/factura.html.twig', ["factura" => $Factura]);
        $filename = "Factura-" . $Factura->getCliente()->getNif() . '-' . $Factura->getSerie() . '-' . $Factura->getNumero() . '.pdf';
        return new PdfResponse($pdf->getOutputFromHtml($html), $filename);

    }

    /**
     * @Route("/factura/exportar/", name="exportar_facturas")
     * @return Response
     */
    public function exportarFacturas(Request $request): Response
    {
        $form = $this->createForm(FiltroFechasType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $fechaInicio = $form["fechaInicio"]->getData();
            $fechaFin = $form["fechaFin"]->getData();
            $Facturas = $this->getDoctrine()->getManager()->getRepository("App:Factura")
                ->createQueryBuilder('u')
                ->where('u.fechaFactura between :fechaInicio and :fechaFin')
                ->setParameter('fechaInicio', $fechaInicio)
                ->setParameter('fechaFin',$fechaFin)
                ->orderBy('u.serie, u.numero')
                ->getQuery()->getResult();
            return $this->exportar($Facturas,$fechaInicio,$fechaFin);
        }

        return $this->render('factura/exportarFactura.html.twig', ["form" => $form->createView()]);

    }


    /**
     * @param $Facturas
     * @param \DateTime $fechaInicio
     * @param \DateTime $fechaFin
     * @return Response
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Reader\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     */
    public function exportar($Facturas, \DateTime $fechaInicio, \DateTime $fechaFin): Response
    {

        $reader = IOFactory::createReader('Xlsx');
        /** @var Spreadsheet $sheet */
        $Spreadsheet = $reader->load('Plantillas/PlantillaFacturas.xlsx');
        $sheet = $Spreadsheet->getActiveSheet();
        $sheet->setCellValue('F10', "Selección=> Desde:". $fechaInicio->format('d/m/Y').
            '  HASTA: '. $fechaFin->format('D/m/Y'));

templates/factura/exportarFactura.html.twig
{% extends "base.html.twig" %}
{% block title %} CONSULTA DE FACTURAS  DE CLIENTE {% endblock %}
{% block titulo %}
    <div id='dtitulo' class="container">
        EXPORTAR FACTURAS
    </div>
{% endblock %}
{% block contenido %}
    <div class="container">
        {{ form_start (form,{'action':'','method':'POST'}) }}
        {{ form_errors(form) }}
        <div class="form-row">{{ form_row(form.fechaInicio) }}</div>
        <div class="form-row">{{ form_row(form.fechaFin) }}</div>
        <div class="form-row">
            <div class="form-group col-md-1">{{ form_row(form.Guardar) }}</div>
        </div>
        {{ form_end (form) }}
    </div>
{% endblock %}

templates/factura/factura.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" lang="es">
    <title>Factura</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
    {# Bootstrap #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <div style="margin-top: 10px">
        <table>
            <tr>
                <td style="width: 50%;text-align: center"><img src="{{ absolute_url(asset("build/logoAceara.jpg")) }}"
                                                               style="width:200px;height:200px"></td>
                <td style="width: 50%;font-size:26px; text-emphasis: #080808">
                    <span>C/VITORIA, 10 LOCAL 3</span> <br/>
                    <span>28941 FUENLABRADA (Madrid)</span> <br/>
                    <span>Teléfono: 916.069.306</span> <br/>
                    <span>C.I.F.: 00277937M</span>
                </td>
            </tr>
        </table>
    </div>
</head>
<body>
<div style="margin-left: 100px;margin-top: 10px">
    <table style="margin-left: 60px">
        <tr>
            <td style="text-align: left;width: 200px;font-weight: bold">NOMBRE Y APELLIDOS:</td>
            <td style="text-align: left;font-style: italic;">{{ factura.cliente.apenom }}</td>
        </tr>
        <tr>
            <td style="text-align: left;width: 200px;font-weight: bold">NIF :</td>
            <td style="text-align: left;font-style: italic;">{{ factura.cliente.nif }}</td>
        </tr>
        <tr>
            <td style="text-align: left;width: 200px;font-weight: bold">DOMICILIO :</td>
            <td style="text-align: left;font-style: italic">{{ factura.cliente.domicilio }}</td>
        </tr>
        <tr>
            <td></td>
            <td style="text-align: left;font-style: italic;">{{ factura.cliente.codigoPostal }} {{ factura.cliente.localidad.descripcion }}</td>
        </tr>
    </table>
</div>
<div style="margin-left: 100px;margin-top: 10px">
    <table style="margin-left: 20px">
        <tr>
            <td style="text-align: left;width: 140px;font-weight: bold">FACTURA Nº :</td>
            <td style="text-align: left;font-style: italic;">{{ factura.serie }}/{{ factura.numero }}</td>
        </tr>
        <tr>
            <td style="text-align: left;width: 140px;font-weight: bold">FECHA FACTURA :</td>
            <td style="text-align: left;font-style: italic;">{{ factura.fechaFactura|date('d/m/Y') }}</td>
        </tr>
    </table>
</div>
<div style="margin-left: 50px; height: 700px;margin-top: 10px;border: thin #000;">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th style="text-align: center;width: 10%">Cantidad</th>
            <th style="text-align: center;width: 50%">Concepto</th>
            <th style="text-align: center;width: 20%">Precio Unitario</th>
            <th style="text-align: center;width: 20%">Importe</th>
        </tr>
        </thead>
        <tbody>
        {% for lineafactura in factura.facturaLineas %}
            <tr>
                <td style="width: auto">{{ lineafactura.unidades }}</td>
                <td style="width: 200px;margin-left: 10px">{{ lineafactura.concepto }}</td>
                <td style="width: auto;text-align: right">{{ lineafactura.importeUnitario| number_format(2,',','.') }}
                    €
                </td>
                <td style="width: auto;text-align: right">{{ lineafactura.importeConcepto |number_format(2,',','.') }}
                    €
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div style="margin-left: 50px;height: 200px">
    <table class="table table-bordered">
        <thead>
        <tr>
            <td style="width: auto;text-align: center;background-color: #b1b0b0">BASE IMPONIBLE</td>
            <td style="width: auto;text-align: center;background-color: #b1b0b0">IVA (21%)</td>
            <td style="width: auto;text-align: center;background-color: #b1b0b0">TOTAL FACTURA</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td style="width: auto;text-align: right">{{ factura.totalConcepto| number_format(2,',','.') }} €</td>
            <td style="width: auto;text-align: right">{{ factura.totalCuotaIva |number_format(2,',','.') }} €</td>
            <td style="width: auto;text-align: right">{{ factura.totalFactura |number_format(2,',','.') }} €</td>
        </tr>
        </tbody>
    </table>
</div>

</body>
<footer>
    <table>
        <tr>
            <td style="width: 33%;">{{ factura.serie }}/ {{ factura.numero }}</td>
            <td style="width: 33%;" class="right">&copy; Centro de Masajes Aceara {{ "now"|date("Y") }}</td>
        </tr>
    </table>
</footer>

</html>

templates/factura/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FacturaController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/jose/htdocs/gestion-aceara/src/Controller/FacturaController.php'|file_link(0) }}">src/Controller/FacturaController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/jose/htdocs/gestion-aceara/templates/factura/index.html.twig'|file_link(0) }}">templates/factura/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/factura/queryFacturas.html.twig
{% extends "base.html.twig" %}
{% block title %} CONSULTA FACTURAS {% endblock %}
{% block titulo %}
    <div id='dtitulo' class="container"> CONSULTA FACTURAS
        {#        <a href="#"#}
        {#           class="btn btn-success">#}
        {#            <span class="glyphicon glyphicon-new-window"></span> Nuevo Tratamiento</a>#}
        {#        <hr/>#}
    </div>
{% endblock %}

{% block contenido %}
    <div class="container">
        {% for message in app.session.flashbag().get('info') %}
            <div class="alert alert-info">{{ message }}</div>
        {% endfor %}
        {% for message in app.session.flashbag().get('error') %}
            <div class="alert alert-danger"> {{ message }} </div>
        {% endfor %}
    </div>

    <div class="container">
        <table id="tablaFacturas" class="tabla table table-striped table-bordered">
            <thead>
            <tr>
                <th>id</th>
                <th>Fecha</th>
                <th>Serie</th>
                <th>Número</th>
                <th>Cliente</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            {% for registro in facturas %}
                <tr>
                    <td>{{ registro.id }}</td>
                    <td>{{ registro.fechaFactura|date ('Y-m-d') }}</td>
                    <td>{{ registro.serie }}</td>
                    <td>{{ registro.numero }}</td>
                    <td>
                        <a href="{{ path("edit_cliente",{"cliente_id":registro.cliente.id}) }}">
                        {{ registro.cliente.apellido1 }} {{ registro.cliente.apellido2 }}
                            , {{ registro.cliente.nombre }}</a> </td>
                    <td>
                        <a href="{{ path("ver_factura",{"factura_id":registro.id}) }}">
                            <span class="glyphicon glyphicon-edit"></span> </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}